# Display message to the standard output
print("System Failure Imminent!")
print("System reboot has been initiated...")
print("")
print("")
print("...Rebooting sensory system")
print("...Rebooting output motors")
print("...Rebooting hover engine")
Print("")
print("System online.")